version: '3.3'

volumes:
  pg_data_production:
  static_volume:
  media_production:

services:

  dbfg:
    image: postgres:13
    volumes:
      - pg_data_production:/var/lib/postgresql/data
    env_file:
      - ./.env

  backend:
    image: krispushka/foodgram_backend
    env_file:
      - ./.env
    depends_on:
      - dbfg
    volumes:
      - static_volume:/backend_static
      - media_production:/app/media/recipes/images/
  frontend:
    image: krispushka/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/staticfiles/
      - media_production:/media/recipes/images/
