version: '3.3'

volumes:
  pg_data_fg:
  static_fg:
  media_foodgram:

services:

  dbfg:
    image: postgres:13
    volumes:
      - pg_data_fg:/var/lib/postgresql/data
    env_file:
      - ./.env

  backend:
    build: ../backend
    env_file:
      - ./.env
    depends_on:
      - dbfg
    volumes:
      - static_fg:/backend_static
      - media_foodgram:/app/media/recipes/images/
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_fg:/frontend_static
    depends_on:
      - backend
  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_fg:/staticfiles/
      - media_foodgram:/media/recipes/images/
